### PR TITLE
Fix the document ready post

### LINKED ISSUE #134: "Execute code when the document is ready" is too naive
The current snippet is:

```
document.addEventListener('DOMContentLoaded', function(){
    ...
});
```

This works only if the user script is executed before the `DOMContentLoaded` event is fired. Proper solution should first check the current `document.readyState` and then either execute the callback immediately or subscribe to the event.

### PR DESCRIPTION
**Pull request by phuoc-ng**
should fix #134

### CODE REVIEW

**Comment by phuoc-ng** [comment]
@dmitryshimkin Can you take a look?

File: client/posts/execute-code-when-the-document-is-ready/index.tsx [hunk 1]
```diff
@@ -7,7 +7,16 @@ export default () => {
 <Markdown
     content={`
 ~~~ javascript
-document.addEventListener('DOMContentLoaded', function(){
+const ready = function(cb) {
+    // Check if the \`document\` is loaded completely
+    (document.readyState === 'complete')
```
Comment (dmitryshimkin) [inline client/posts/execute-code-when-the-document-is-ready/index.tsx:12]: I would probably change the check to the following:

```
(document.readyState === 'loading')
  ? document.addEventListener('DOMContentLoaded', cb)
  : cb();
```

IIRC this will cover the case when the DCL event is already fired but the `readyState` is not `complete` yet (e.g. it is `interactive`).

Comment (dmitryshimkin) [reply client/posts/execute-code-when-the-document-is-ready/index.tsx:12]: One more remark. The `cb` is called inconsistently. When called directly it receives no parameters, but when it is passed as the event listener it receives the event object as a parameter.

This issue is minor though. Not sure what level of correctness is expected here :-)

Comment (phuoc-ng) [reply client/posts/execute-code-when-the-document-is-ready/index.tsx]: Thanks for the comments!
Regarding the level of correctness, of course, we always try our best.
